require("core.options")
require("core.keymaps")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.plugins-setup")
require("plugins.gitsigns")
require("plugins.telescope")
-- require('plugins.rainbow')
require("plugins.fitten-code")
require("plugins.nlf")
require("plugins.bufferline")
